[package]
name = "day7"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
aoc = { version = "0.1.0", path = "../aoc" }
rayon = { workspace = true }
itertools = { workspace = true }
radix_fmt = "1.0.0"
